Bipu
gtrcamryr34/frameworkPlayground pull request #2
Opened 2020-01-03 06:32 UTC by bariul28

please reply me back

2020-01-03 17:23 UTC, ashraf1190 requested changes
There are a few things missing in this test 

1. How do we know that those options are selected? You can use a method to verify if the checkboxes are selected.
2. The CheckBoxesPage.java is basically empty? WHY?
3. Verify title on CheckBoxesPage so you know youre on the correct page

2020-01-03 17:23 UTC, ashraf1190 commented on src/main/java/pages/CheckBoxesPage.java
> +    private String loginURL = "http://the-internet.herokuapp.com/checkboxes";
this is not a login URL

2020-01-03 17:23 UTC, ashraf1190 commented on src/main/java/pages/HomeScreen.java
> +    private By checkBoxoption1 = By.xpath ("//*[@id=\"checkboxes\"]/input[1]");
this should be in CheckBoxesPage.java

2020-01-03 17:23 UTC, ashraf1190 commented on src/main/java/pages/HomeScreen.java
> +    private By checkBoxoption2 = By.xpath("//*[@id=\"checkboxes\"]/input[2]");
this should be in CheckBoxesPage.java

2020-01-03 17:23 UTC, ashraf1190 commented on src/main/java/pages/HomeScreen.java
> +    public void clickoption1() {click (checkBoxoption1);}
this should be in CheckBoxesPage.java

2020-01-03 17:23 UTC, ashraf1190 commented on src/main/java/pages/HomeScreen.java
> +    public void clickoption2() {click ( checkBoxoption2 );}
this should be in CheckBoxesPage.java

2020-01-03 19:22 UTC, bariul28 commented on src/main/java/pages/CheckBoxesPage.java
> +    private String loginURL = "http://the-internet.herokuapp.com/checkboxes";
ok i will. and send you to review

2020-01-03 19:23 UTC, bariul28 commented on src/main/java/pages/HomeScreen.java
> +    private By checkBoxoption1 = By.xpath ("//*[@id=\"checkboxes\"]/input[1]");
ok

2020-01-03 19:23 UTC, bariul28 commented on src/main/java/pages/HomeScreen.java
> +    public void clickoption1() {click (checkBoxoption1);}
ok

2020-01-03 19:24 UTC, bariul28 commented
thanks for your valuable review.

2020-01-06 06:13 UTC, bariul28 reviewed
please review my work @ashraf1190

2020-01-17 04:47 UTC, ashraf1190 approved these changes

2020-01-17 04:48 UTC, ashraf1190 commented
Everything looks good I will merge your changes

2020-01-17 04:48 UTC, merged